export const MANAUS_NEIGHBORHOODS = [
  'Adrianópolis',
  'Aleixo',
  'Alfa Village',
  'Alvorada',
  'Armando Mendes',
  'Betânia',
  'Cachoeirinha',
  'Centro',
  'Chapada',
  'Cidade Nova',
  'Colônia Terra Nova',
  'Compensa',
  'Coroado',
  'Crespo',
  'Distrito Industrial I',
  'Distrito Industrial II',
  'Dom Pedro',
  'Educandos',
  'Flores',
  'Japiim',
  'Jorge Teixeira',
  'Lago Azul',
  'Lírio do Vale',
  'Manaus2000',
  'Nossa Senhora das Graças / Vieiralves',
  'Nova Cidade',
  'Novo Aleixo',
  'Novo Israel',
  'Parque 10 de Novembro',
  'Petrópolis',
  'Planalto',
  'Ponta Negra',
  'Praça 14 de Janeiro',
  'Raiz',
  'Redenção',
  'Santa Etelvina',
  'Santo Antônio',
  'São Francisco',
  'São Geraldo',
  'São Jorge',
  'São José Operário',
  'Tarumã',
  'Tarumã-Açú',
  'Vila da Prata',
  'Zumbi dos Palmares'
];

export const PROPERTY_CATEGORIES = [
  'Apartamento',
  'Casa',
  'Casa em Condomínio',
  'Cobertura',
  'Flat / Studio / Kitnet',
  'Terreno / Lote',
  'Terreno em Condomínio',
  'Sala Comercial',
  'Prédio Comercial',
  'Loja / Ponto Comercial',
  'Galpão / Depósito / Armazém',
  'Chácara / Sítio / Fazenda',
  'Área Industrial',
  'Loft',
  'Duplex / Triplex',
  'Sobrado',
  'Hotel / Pousada',
  'Outro'
] as const;
